name: '🐞 버그'
description: '발견한 버그를 보고해주세요. 자세한 정보를 포함해 주시면 큰 도움이 됩니다!'
title: '[BUG] - 간단한 문제 설명'
labels:
  - bug
  - needs triage
assignees:
  - ''

body:
  - type: markdown
    attributes:
      value: |
        아래 템플릿을 따라 버그를 보고해주세요. 필요한 정보를 모두 작성해주세요.

  - type: input
    id: bug_description
    attributes:
      label: '버그 설명'
      description: '발생한 버그에 대해 명확하고 간결하게 설명해주세요.'
      placeholder: '버그가 무엇인지 간단히 적어주세요.'

  - type: textarea
    id: reproduce_steps
    attributes:
      label: '재현 방법'
      description: "버그를 재현하기 위한 단계(예: 1. '...'로 이동, 2. '...' 클릭)를 작성해주세요."
      placeholder: |
        1. '...'로 이동
        2. '...'를 클릭
        3. '...'로 스크롤
        4. 오류를 확인

  - type: input
    id: expected_behavior
    attributes:
      label: '예상 동작'
      description: '기대했던 동작을 간결하게 설명해주세요.'
      placeholder: '정상적으로 작동할 경우 어떻게 보여야 하나요?'

  - type: textarea
    id: additional_context
    attributes:
      label: '추가 정보'
      description: '문제와 관련된 추가적인 정보를 작성해주세요.'
      placeholder: '추가 정보를 입력하세요 (선택 사항).'
