name: '♻️ 리팩토링 요청'
description: '코드 개선이나 리팩토링이 필요한 부분을 보고해주세요.'
title: '[REFACTOR] - 간단한 리팩토링 요청 내용'
labels:
  - refactor
  - enhancement
assignees:
  - ''

body:
  - type: markdown
    attributes:
      value: |
        아래 템플릿을 따라 리팩토링 요청 내용을 작성해주세요.

  - type: input
    id: refactoring_area
    attributes:
      label: '리팩토링 대상'
      description: '리팩토링이 필요한 코드 영역이나 파일을 명시해주세요.'
      placeholder: '예: components/Button.js, utils/apiHandler.js'

  - type: textarea
    id: current_issue
    attributes:
      label: '현재 문제점'
      description: '현재 코드에서 개선이 필요한 문제점이나 비효율적인 부분을 설명해주세요.'
      placeholder: |
        - 코드가 중복되어 유지보수가 어렵습니다.
        - 가독성이 떨어집니다.
        - 성능 문제가 있습니다.

  - type: textarea
    id: refactoring_scope
    attributes:
      label: '리팩토링 범위'
      description: '리팩토링이 적용될 구체적인 범위를 작성해주세요.'
      placeholder: |
        - 특정 컴포넌트/모듈
        - 기능 단위 코드
        - 전체적인 코드 구조

  - type: textarea
    id: expected_outcome
    attributes:
      label: '예상 효과'
      description: '리팩토링 완료 후 기대되는 결과를 작성해주세요.'
      placeholder: |
        - 가독성 향상
        - 성능 최적화
        - 코드 재사용성 증대

  - type: dropdown
    id: priority
    attributes:
      label: '우선순위'
      description: '리팩토링의 우선순위를 설정해주세요.'
      options:
        - '낮음'
        - '보통'
        - '높음'

  - type: textarea
    id: additional_context
    attributes:
      label: '추가 정보'
      description: '리팩토링과 관련된 추가적인 정보를 작성해주세요.'
      placeholder: '관련 자료 링크, 참고할 문서, 팀 내 논의 사항 등을 작성하세요.'
